// <auto-generated />
using System;
using Banana_E_Commerce_API.Helpers;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Banana_E_Commerce_API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20200528080231_Product_Seed_Data")]
    partial class Product_Seed_Data
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Banana_E_Commerce_API.Entities.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("District")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StreetLocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Ward")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("Banana_E_Commerce_API.Entities.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("Banana_E_Commerce_API.Entities.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId")
                        .IsUnique();

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("Banana_E_Commerce_API.Entities.CartDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductTierId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.HasIndex("ProductTierId");

                    b.ToTable("CartDetails");
                });

            modelBuilder.Entity("Banana_E_Commerce_API.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2020, 5, 28, 8, 2, 28, 936, DateTimeKind.Utc).AddTicks(6946),
                            CreatedBy = 1,
                            IsDeleted = false,
                            Name = "Trái Cây Việt",
                            UpdatedAt = new DateTime(2020, 5, 28, 8, 2, 28, 936, DateTimeKind.Utc).AddTicks(7408)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2020, 5, 28, 8, 2, 28, 936, DateTimeKind.Utc).AddTicks(8595),
                            CreatedBy = 2,
                            IsDeleted = false,
                            Name = "Trái Cây Nhập",
                            UpdatedAt = new DateTime(2020, 5, 28, 8, 2, 28, 936, DateTimeKind.Utc).AddTicks(8624)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2020, 5, 28, 8, 2, 28, 936, DateTimeKind.Utc).AddTicks(8657),
                            CreatedBy = 3,
                            IsDeleted = false,
                            Name = "Trái Cây Sấy Khô",
                            UpdatedAt = new DateTime(2020, 5, 28, 8, 2, 28, 936, DateTimeKind.Utc).AddTicks(8659)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2020, 5, 28, 8, 2, 28, 936, DateTimeKind.Utc).AddTicks(8661),
                            CreatedBy = 4,
                            IsDeleted = false,
                            Name = "Mứt Trái Cây>",
                            UpdatedAt = new DateTime(2020, 5, 28, 8, 2, 28, 936, DateTimeKind.Utc).AddTicks(8663)
                        });
                });

            modelBuilder.Entity("Banana_E_Commerce_API.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("Banana_E_Commerce_API.Entities.ImportBill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Currency")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("RequestImportProductId")
                        .HasColumnType("int");

                    b.Property<int>("StorageId")
                        .HasColumnType("int");

                    b.Property<int>("StorageManagerId")
                        .HasColumnType("int");

                    b.Property<double>("TotalAmount")
                        .HasColumnType("float");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("RequestImportProductId");

                    b.HasIndex("StorageId");

                    b.HasIndex("StorageManagerId");

                    b.ToTable("ImportBills");
                });

            modelBuilder.Entity("Banana_E_Commerce_API.Entities.ImportBillDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ImportBillId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<double>("Quantity")
                        .HasColumnType("float");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ImportBillId");

                    b.HasIndex("ProductId");

                    b.ToTable("ImportBillDetails");
                });

            modelBuilder.Entity("Banana_E_Commerce_API.Entities.ImportProductReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NextImportTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReportImageLocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RequestImportProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("RequestImportProductId");

                    b.ToTable("ImportProductReports");
                });

            modelBuilder.Entity("Banana_E_Commerce_API.Entities.Invoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("PaymentMethodId")
                        .HasColumnType("int");

                    b.Property<int>("ShipmentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PaymentMethodId");

                    b.HasIndex("ShipmentId")
                        .IsUnique();

                    b.ToTable("Invoice");
                });

            modelBuilder.Entity("Banana_E_Commerce_API.Entities.Manager", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Managers");
                });

            modelBuilder.Entity("Banana_E_Commerce_API.Entities.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("NotificationTo")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("NotificationTo");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("Banana_E_Commerce_API.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AddressId")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Currency")
                        .HasColumnType("int");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("IdealShipTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCustomerReceive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsGift")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderStatus")
                        .HasColumnType("int");

                    b.Property<double>("TotalAmount")
                        .HasColumnType("float");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AddressId")
                        .IsUnique();

                    b.HasIndex("CustomerId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Banana_E_Commerce_API.Entities.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductTierId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("SinglePrice")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductTierId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("Banana_E_Commerce_API.Entities.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AdminId")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Currency")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ExportBy")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<double>("TotalAmount")
                        .HasColumnType("float");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AdminId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("Banana_E_Commerce_API.Entities.PaymentMethod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Method")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.ToTable("PaymentMethods");
                });

            modelBuilder.Entity("Banana_E_Commerce_API.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("EntryPrice")
                        .HasColumnType("float");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Origin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PriceCurrency")
                        .HasColumnType("int");

                    b.Property<int>("ProductUnit")
                        .HasColumnType("int");

                    b.Property<int>("StorageId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("StorageId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2020, 5, 28, 8, 2, 28, 937, DateTimeKind.Utc).AddTicks(2397),
                            CreatedBy = 1,
                            Description = "Bơ 034 từ Việt Nam, Đắk Lắk",
                            EntryPrice = 60000.0,
                            IsDeleted = false,
                            Name = "Bơ 034",
                            Origin = "Việt Nam, Đắk Lắk",
                            PriceCurrency = 1,
                            ProductUnit = 7,
                            StorageId = 1,
                            UpdatedAt = new DateTime(2020, 5, 28, 8, 2, 28, 937, DateTimeKind.Utc).AddTicks(2879)
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2020, 5, 28, 8, 2, 28, 937, DateTimeKind.Utc).AddTicks(4775),
                            CreatedBy = 2,
                            Description = "Bơ Sáp từ Việt Nam, Đắk Lắk",
                            EntryPrice = 58000.0,
                            IsDeleted = false,
                            Name = "Bơ Sáp",
                            Origin = "Việt Nam, Đắk Lắk",
                            PriceCurrency = 1,
                            ProductUnit = 7,
                            StorageId = 1,
                            UpdatedAt = new DateTime(2020, 5, 28, 8, 2, 28, 937, DateTimeKind.Utc).AddTicks(4789)
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2020, 5, 28, 8, 2, 28, 937, DateTimeKind.Utc).AddTicks(4843),
                            CreatedBy = 3,
                            Description = "Bưởi Da Xanh từ Việt Nam, Đồng Nai, Tân Triều",
                            EntryPrice = 30000.0,
                            IsDeleted = false,
                            Name = "Bưởi Da Xanh",
                            Origin = "Việt Nam, Đồng Nai, Tân Triều",
                            PriceCurrency = 1,
                            ProductUnit = 3,
                            StorageId = 1,
                            UpdatedAt = new DateTime(2020, 5, 28, 8, 2, 28, 937, DateTimeKind.Utc).AddTicks(4845)
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2020, 5, 28, 8, 2, 28, 937, DateTimeKind.Utc).AddTicks(4849),
                            CreatedBy = 3,
                            Description = "Có sắc tố đặc biệt, rất hiệu dụng trong quá trình chống oxy hóa",
                            EntryPrice = 65000.0,
                            IsDeleted = false,
                            Name = "Cà Chua Đen",
                            Origin = "Hà Nội",
                            PriceCurrency = 1,
                            ProductUnit = 7,
                            StorageId = 1,
                            UpdatedAt = new DateTime(2020, 5, 28, 8, 2, 28, 937, DateTimeKind.Utc).AddTicks(4850)
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2020, 5, 28, 8, 2, 28, 937, DateTimeKind.Utc).AddTicks(4853),
                            CreatedBy = 4,
                            Description = "Cam Sành Miền Tây",
                            EntryPrice = 15000.0,
                            IsDeleted = false,
                            Name = "Cam Sành",
                            Origin = "Miền Tây",
                            PriceCurrency = 1,
                            ProductUnit = 7,
                            StorageId = 1,
                            UpdatedAt = new DateTime(2020, 5, 28, 8, 2, 28, 937, DateTimeKind.Utc).AddTicks(4854)
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2020, 5, 28, 8, 2, 28, 937, DateTimeKind.Utc).AddTicks(4857),
                            CreatedBy = 1,
                            Description = "Chanh đào tươi Đà Lạt",
                            EntryPrice = 40000.0,
                            IsDeleted = false,
                            Name = "Chanh Đào Tươi",
                            Origin = "Đà Lạt",
                            PriceCurrency = 1,
                            ProductUnit = 7,
                            StorageId = 1,
                            UpdatedAt = new DateTime(2020, 5, 28, 8, 2, 28, 937, DateTimeKind.Utc).AddTicks(4858)
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2020, 5, 28, 8, 2, 28, 937, DateTimeKind.Utc).AddTicks(4861),
                            CreatedBy = 2,
                            Description = "Chôm chôm nhãn",
                            EntryPrice = 35000.0,
                            IsDeleted = false,
                            Name = "Chôm Chôm Nhãn",
                            Origin = "Đồng Bằng Sông Cửu Long",
                            PriceCurrency = 1,
                            ProductUnit = 7,
                            StorageId = 1,
                            UpdatedAt = new DateTime(2020, 5, 28, 8, 2, 28, 937, DateTimeKind.Utc).AddTicks(4862)
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2020, 5, 28, 8, 2, 28, 937, DateTimeKind.Utc).AddTicks(4864),
                            CreatedBy = 3,
                            Description = "Nhãn Lồng",
                            EntryPrice = 25000.0,
                            IsDeleted = false,
                            Name = "Nhãn Lồng",
                            Origin = "Hưng Yên",
                            PriceCurrency = 1,
                            ProductUnit = 7,
                            StorageId = 1,
                            UpdatedAt = new DateTime(2020, 5, 28, 8, 2, 28, 937, DateTimeKind.Utc).AddTicks(4866)
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2020, 5, 28, 8, 2, 28, 937, DateTimeKind.Utc).AddTicks(4868),
                            CreatedBy = 4,
                            Description = "Thanh Long Ruột Đỏ",
                            EntryPrice = 22000.0,
                            IsDeleted = false,
                            Name = "Thanh Long Ruột Đỏ",
                            Origin = "Bình Thuận",
                            PriceCurrency = 1,
                            ProductUnit = 7,
                            StorageId = 1,
                            UpdatedAt = new DateTime(2020, 5, 28, 8, 2, 28, 937, DateTimeKind.Utc).AddTicks(4870)
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2020, 5, 28, 8, 2, 28, 937, DateTimeKind.Utc).AddTicks(4872),
                            CreatedBy = 1,
                            Description = "Thanh long ruột trắng",
                            EntryPrice = 25000.0,
                            IsDeleted = false,
                            Name = "Thanh Long Ruột Trắng",
                            Origin = "Bình Thuận",
                            PriceCurrency = 1,
                            ProductUnit = 7,
                            StorageId = 1,
                            UpdatedAt = new DateTime(2020, 5, 28, 8, 2, 28, 937, DateTimeKind.Utc).AddTicks(4874)
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2020, 5, 28, 8, 2, 28, 937, DateTimeKind.Utc).AddTicks(4877),
                            CreatedBy = 2,
                            Description = "Dâu tây đà lạt giống Mỹ",
                            EntryPrice = 120000.0,
                            IsDeleted = false,
                            Name = "Dâu Tây Đà Lạt",
                            Origin = "Đà Lạt",
                            PriceCurrency = 1,
                            ProductUnit = 7,
                            StorageId = 1,
                            UpdatedAt = new DateTime(2020, 5, 28, 8, 2, 28, 937, DateTimeKind.Utc).AddTicks(4878)
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2020, 5, 28, 8, 2, 28, 937, DateTimeKind.Utc).AddTicks(4880),
                            CreatedBy = 3,
                            Description = "Dưa lưới Bình Dương",
                            EntryPrice = 30000.0,
                            IsDeleted = false,
                            Name = "Dưa Lưới",
                            Origin = "Bình Dương",
                            PriceCurrency = 1,
                            ProductUnit = 7,
                            StorageId = 1,
                            UpdatedAt = new DateTime(2020, 5, 28, 8, 2, 28, 937, DateTimeKind.Utc).AddTicks(4882)
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2020, 5, 28, 8, 2, 28, 937, DateTimeKind.Utc).AddTicks(4885),
                            CreatedBy = 4,
                            Description = "Dưa Pepino Mexico",
                            EntryPrice = 45000.0,
                            IsDeleted = false,
                            Name = "Dưới Pepino",
                            Origin = "Mexico",
                            PriceCurrency = 1,
                            ProductUnit = 7,
                            StorageId = 1,
                            UpdatedAt = new DateTime(2020, 5, 28, 8, 2, 28, 937, DateTimeKind.Utc).AddTicks(4886)
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2020, 5, 28, 8, 2, 28, 937, DateTimeKind.Utc).AddTicks(4888),
                            CreatedBy = 1,
                            Description = "Cherry Mỹ",
                            EntryPrice = 310000.0,
                            IsDeleted = false,
                            Name = "Cherry Mỹ",
                            Origin = "Mỹ",
                            PriceCurrency = 1,
                            ProductUnit = 7,
                            StorageId = 1,
                            UpdatedAt = new DateTime(2020, 5, 28, 8, 2, 28, 937, DateTimeKind.Utc).AddTicks(4890)
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2020, 5, 28, 8, 2, 28, 937, DateTimeKind.Utc).AddTicks(4892),
                            CreatedBy = 2,
                            Description = "Việt Quất Mỹ",
                            EntryPrice = 380000.0,
                            IsDeleted = false,
                            Name = "Việt Quất Mỹ",
                            Origin = "Mỹ",
                            PriceCurrency = 1,
                            ProductUnit = 7,
                            StorageId = 1,
                            UpdatedAt = new DateTime(2020, 5, 28, 8, 2, 28, 937, DateTimeKind.Utc).AddTicks(4894)
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2020, 5, 28, 8, 2, 28, 937, DateTimeKind.Utc).AddTicks(4896),
                            CreatedBy = 3,
                            Description = "Dưa Lê Hàn",
                            EntryPrice = 180000.0,
                            IsDeleted = false,
                            Name = "Dưa Lê Hàn",
                            Origin = "Hàn Quốc",
                            PriceCurrency = 1,
                            ProductUnit = 7,
                            StorageId = 1,
                            UpdatedAt = new DateTime(2020, 5, 28, 8, 2, 28, 937, DateTimeKind.Utc).AddTicks(4898)
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2020, 5, 28, 8, 2, 28, 937, DateTimeKind.Utc).AddTicks(4900),
                            CreatedBy = 4,
                            Description = "Táo New Zealand",
                            EntryPrice = 200000.0,
                            IsDeleted = false,
                            Name = "Táo New Zealand",
                            Origin = "New Zealand",
                            PriceCurrency = 1,
                            ProductUnit = 7,
                            StorageId = 1,
                            UpdatedAt = new DateTime(2020, 5, 28, 8, 2, 28, 937, DateTimeKind.Utc).AddTicks(4901)
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2020, 5, 28, 8, 2, 28, 937, DateTimeKind.Utc).AddTicks(4904),
                            CreatedBy = 1,
                            Description = "Kiwi Vàng New Zealand ",
                            EntryPrice = 130000.0,
                            IsDeleted = false,
                            Name = "Kiwi Vàng New Zealand ",
                            Origin = "New Zealand",
                            PriceCurrency = 1,
                            ProductUnit = 7,
                            StorageId = 1,
                            UpdatedAt = new DateTime(2020, 5, 28, 8, 2, 28, 937, DateTimeKind.Utc).AddTicks(4905)
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2020, 5, 28, 8, 2, 28, 937, DateTimeKind.Utc).AddTicks(4908),
                            CreatedBy = 2,
                            Description = "Nho xanh Úc",
                            EntryPrice = 320000.0,
                            IsDeleted = false,
                            Name = "Nho xanh Úc",
                            Origin = "Úc",
                            PriceCurrency = 1,
                            ProductUnit = 7,
                            StorageId = 1,
                            UpdatedAt = new DateTime(2020, 5, 28, 8, 2, 28, 937, DateTimeKind.Utc).AddTicks(4909)
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2020, 5, 28, 8, 2, 28, 937, DateTimeKind.Utc).AddTicks(4912),
                            CreatedBy = 3,
                            Description = "Dâu Anh Đào Nhật",
                            EntryPrice = 610000.0,
                            IsDeleted = false,
                            Name = "Dâu Anh Đào Nhật",
                            Origin = "Nhật Bản",
                            PriceCurrency = 1,
                            ProductUnit = 8,
                            StorageId = 1,
                            UpdatedAt = new DateTime(2020, 5, 28, 8, 2, 28, 937, DateTimeKind.Utc).AddTicks(4913)
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2020, 5, 28, 8, 2, 28, 937, DateTimeKind.Utc).AddTicks(4916),
                            CreatedBy = 4,
                            Description = "Dưa Hấu Luna Piena Nhật",
                            EntryPrice = 170000.0,
                            IsDeleted = false,
                            Name = "Dưa Hấu Luna Piena Nhật",
                            Origin = "Nhật Bản",
                            PriceCurrency = 1,
                            ProductUnit = 3,
                            StorageId = 1,
                            UpdatedAt = new DateTime(2020, 5, 28, 8, 2, 28, 937, DateTimeKind.Utc).AddTicks(4917)
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2020, 5, 28, 8, 2, 28, 937, DateTimeKind.Utc).AddTicks(4920),
                            CreatedBy = 1,
                            Description = "Sầu Riêng Muthong Thái",
                            EntryPrice = 100000.0,
                            IsDeleted = false,
                            Name = "Sầu Riêng Muthong Thái",
                            Origin = "Thái Lan",
                            PriceCurrency = 1,
                            ProductUnit = 7,
                            StorageId = 1,
                            UpdatedAt = new DateTime(2020, 5, 28, 8, 2, 28, 937, DateTimeKind.Utc).AddTicks(4921)
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2020, 5, 28, 8, 2, 28, 937, DateTimeKind.Utc).AddTicks(4924),
                            CreatedBy = 2,
                            Description = "Bơ Úc (Bơ Hass)",
                            EntryPrice = 140000.0,
                            IsDeleted = false,
                            Name = "Bơ Úc (Bơ Hass)",
                            Origin = "Úc",
                            PriceCurrency = 1,
                            ProductUnit = 7,
                            StorageId = 1,
                            UpdatedAt = new DateTime(2020, 5, 28, 8, 2, 28, 937, DateTimeKind.Utc).AddTicks(4925)
                        });
                });

            modelBuilder.Entity("Banana_E_Commerce_API.Entities.ProductExportBill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("RequestExportProductId")
                        .HasColumnType("int");

                    b.Property<int>("StorageManagerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("RequestExportProductId");

                    b.HasIndex("StorageManagerId");

                    b.ToTable("ProductExportBills");
                });

            modelBuilder.Entity("Banana_E_Commerce_API.Entities.ProductExportDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ExportBillId")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("ProductTierId")
                        .HasColumnType("int");

                    b.Property<double>("Quantity")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("ExportBillId");

                    b.HasIndex("ProductTierId");

                    b.ToTable("ProductExportDetails");
                });

            modelBuilder.Entity("Banana_E_Commerce_API.Entities.ProductFavorite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("ProductTierId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ProductTierId");

                    b.ToTable("ProductFavorites");
                });

            modelBuilder.Entity("Banana_E_Commerce_API.Entities.ProductImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImgLocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImgName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductImages");
                });

            modelBuilder.Entity("Banana_E_Commerce_API.Entities.ProductTier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("AfterDiscountPrice")
                        .HasColumnType("float");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DiscountPercentage")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<double>("KgSale")
                        .HasColumnType("float");

                    b.Property<int>("PriceCurrency")
                        .HasColumnType("int");

                    b.Property<double>("PricePerKg")
                        .HasColumnType("float");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<double>("Quantity")
                        .HasColumnType("float");

                    b.Property<double>("SalePrice")
                        .HasColumnType("float");

                    b.Property<int>("TierId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("TierId");

                    b.ToTable("ProductTiers");
                });

            modelBuilder.Entity("Banana_E_Commerce_API.Entities.Rating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Like")
                        .HasColumnType("int");

                    b.Property<int>("ProductTierId")
                        .HasColumnType("int");

                    b.Property<int>("StarNum")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ProductTierId");

                    b.ToTable("Rates");
                });

            modelBuilder.Entity("Banana_E_Commerce_API.Entities.RefreshToken", b =>
                {
                    b.Property<string>("Token")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsValidated")
                        .HasColumnType("bit");

                    b.Property<string>("JwtId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Token");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshToken");
                });

            modelBuilder.Entity("Banana_E_Commerce_API.Entities.RequestExportDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ProductTierId")
                        .HasColumnType("int");

                    b.Property<double>("Quantity")
                        .HasColumnType("float");

                    b.Property<int>("RequestExportProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductTierId");

                    b.HasIndex("RequestExportProductId");

                    b.ToTable("RequestExportDetails");
                });

            modelBuilder.Entity("Banana_E_Commerce_API.Entities.RequestExportProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.ToTable("RequestExportProducts");
                });

            modelBuilder.Entity("Banana_E_Commerce_API.Entities.RequestImportDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ProductTierId")
                        .HasColumnType("int");

                    b.Property<double>("Quantity")
                        .HasColumnType("float");

                    b.Property<int>("RequestImportProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductTierId");

                    b.HasIndex("RequestImportProductId");

                    b.ToTable("RequestImportDetails");
                });

            modelBuilder.Entity("Banana_E_Commerce_API.Entities.RequestImportProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.ToTable("RequestImportProducts");
                });

            modelBuilder.Entity("Banana_E_Commerce_API.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("RoleName")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2020, 5, 28, 8, 2, 28, 934, DateTimeKind.Utc).AddTicks(2715),
                            IsDeleted = false,
                            RoleName = 0,
                            UpdatedAt = new DateTime(2020, 5, 28, 8, 2, 28, 934, DateTimeKind.Utc).AddTicks(3218)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2020, 5, 28, 8, 2, 28, 934, DateTimeKind.Utc).AddTicks(4044),
                            IsDeleted = false,
                            RoleName = 1,
                            UpdatedAt = new DateTime(2020, 5, 28, 8, 2, 28, 934, DateTimeKind.Utc).AddTicks(4059)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2020, 5, 28, 8, 2, 28, 934, DateTimeKind.Utc).AddTicks(4100),
                            IsDeleted = false,
                            RoleName = 2,
                            UpdatedAt = new DateTime(2020, 5, 28, 8, 2, 28, 934, DateTimeKind.Utc).AddTicks(4102)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2020, 5, 28, 8, 2, 28, 934, DateTimeKind.Utc).AddTicks(4104),
                            IsDeleted = false,
                            RoleName = 3,
                            UpdatedAt = new DateTime(2020, 5, 28, 8, 2, 28, 934, DateTimeKind.Utc).AddTicks(4105)
                        });
                });

            modelBuilder.Entity("Banana_E_Commerce_API.Entities.Shipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AdminId")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("District")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductExportBillId")
                        .HasColumnType("int");

                    b.Property<int>("ShipperId")
                        .HasColumnType("int");

                    b.Property<double>("ShippingCharge")
                        .HasColumnType("float");

                    b.Property<string>("StreetLocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Ward")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AdminId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductExportBillId");

                    b.HasIndex("ShipperId");

                    b.ToTable("Shipment");
                });

            modelBuilder.Entity("Banana_E_Commerce_API.Entities.Shipper", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AdminId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("IdentityId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AdminId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Shipper");
                });

            modelBuilder.Entity("Banana_E_Commerce_API.Entities.Storage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Size")
                        .HasColumnType("float");

                    b.Property<string>("SizeUnit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Storages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2020, 5, 28, 8, 2, 28, 936, DateTimeKind.Utc).AddTicks(3766),
                            CreatedBy = 3,
                            IsDeleted = false,
                            Location = "Tiểu Vương Quốc Bình Chánh",
                            Name = "Hoàng Khố",
                            Size = 1000.2,
                            SizeUnit = "m2",
                            UpdatedAt = new DateTime(2020, 5, 28, 8, 2, 28, 936, DateTimeKind.Utc).AddTicks(4227)
                        });
                });

            modelBuilder.Entity("Banana_E_Commerce_API.Entities.StorageManager", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("BirthDay")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StorageId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StorageId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("StorageManagers");
                });

            modelBuilder.Entity("Banana_E_Commerce_API.Entities.Tier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("TierOption")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Tiers");
                });

            modelBuilder.Entity("Banana_E_Commerce_API.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Banana_E_Commerce_API.Entities.Address", b =>
                {
                    b.HasOne("Banana_E_Commerce_API.Entities.Customer", "Customer")
                        .WithMany("Addresses")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Banana_E_Commerce_API.Entities.Admin", b =>
                {
                    b.HasOne("Banana_E_Commerce_API.Entities.User", "User")
                        .WithOne("Admin")
                        .HasForeignKey("Banana_E_Commerce_API.Entities.Admin", "UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Banana_E_Commerce_API.Entities.Cart", b =>
                {
                    b.HasOne("Banana_E_Commerce_API.Entities.Customer", "Customer")
                        .WithOne("Cart")
                        .HasForeignKey("Banana_E_Commerce_API.Entities.Cart", "CustomerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Banana_E_Commerce_API.Entities.CartDetail", b =>
                {
                    b.HasOne("Banana_E_Commerce_API.Entities.Cart", "Cart")
                        .WithMany("CartDetails")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Banana_E_Commerce_API.Entities.ProductTier", "ProductTier")
                        .WithMany("CartDetails")
                        .HasForeignKey("ProductTierId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Banana_E_Commerce_API.Entities.Category", b =>
                {
                    b.HasOne("Banana_E_Commerce_API.Entities.Admin", "Admin")
                        .WithMany("Categories")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Banana_E_Commerce_API.Entities.Customer", b =>
                {
                    b.HasOne("Banana_E_Commerce_API.Entities.User", "User")
                        .WithOne("Customer")
                        .HasForeignKey("Banana_E_Commerce_API.Entities.Customer", "UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Banana_E_Commerce_API.Entities.ImportBill", b =>
                {
                    b.HasOne("Banana_E_Commerce_API.Entities.RequestImportProduct", "RequestImportProduct")
                        .WithMany("ImportBills")
                        .HasForeignKey("RequestImportProductId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Banana_E_Commerce_API.Entities.Storage", "Storage")
                        .WithMany("ImportBills")
                        .HasForeignKey("StorageId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Banana_E_Commerce_API.Entities.StorageManager", "StorageManager")
                        .WithMany("ImportBills")
                        .HasForeignKey("StorageManagerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Banana_E_Commerce_API.Entities.ImportBillDetail", b =>
                {
                    b.HasOne("Banana_E_Commerce_API.Entities.ImportBill", "ImportBill")
                        .WithMany("ImportBillDetails")
                        .HasForeignKey("ImportBillId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Banana_E_Commerce_API.Entities.Product", "Product")
                        .WithMany("ImportBillDetails")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Banana_E_Commerce_API.Entities.ImportProductReport", b =>
                {
                    b.HasOne("Banana_E_Commerce_API.Entities.StorageManager", "StorageManager")
                        .WithMany("ImportProductReports")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Banana_E_Commerce_API.Entities.RequestImportProduct", "RequestImportProduct")
                        .WithMany("ImportProductReports")
                        .HasForeignKey("RequestImportProductId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Banana_E_Commerce_API.Entities.Invoice", b =>
                {
                    b.HasOne("Banana_E_Commerce_API.Entities.PaymentMethod", "PaymentMethod")
                        .WithMany("Invoices")
                        .HasForeignKey("PaymentMethodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Banana_E_Commerce_API.Entities.Shipment", "Shipment")
                        .WithOne("Invoice")
                        .HasForeignKey("Banana_E_Commerce_API.Entities.Invoice", "ShipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Banana_E_Commerce_API.Entities.Manager", b =>
                {
                    b.HasOne("Banana_E_Commerce_API.Entities.User", "User")
                        .WithOne("Manager")
                        .HasForeignKey("Banana_E_Commerce_API.Entities.Manager", "UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Banana_E_Commerce_API.Entities.Notification", b =>
                {
                    b.HasOne("Banana_E_Commerce_API.Entities.Admin", "Admin")
                        .WithMany("Notifications")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Banana_E_Commerce_API.Entities.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("NotificationTo")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Banana_E_Commerce_API.Entities.Order", b =>
                {
                    b.HasOne("Banana_E_Commerce_API.Entities.Address", "Address")
                        .WithOne("Order")
                        .HasForeignKey("Banana_E_Commerce_API.Entities.Order", "AddressId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Banana_E_Commerce_API.Entities.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Banana_E_Commerce_API.Entities.OrderItem", b =>
                {
                    b.HasOne("Banana_E_Commerce_API.Entities.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Banana_E_Commerce_API.Entities.ProductTier", "ProductTier")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductTierId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Banana_E_Commerce_API.Entities.Payment", b =>
                {
                    b.HasOne("Banana_E_Commerce_API.Entities.Admin", "Admin")
                        .WithMany()
                        .HasForeignKey("AdminId");
                });

            modelBuilder.Entity("Banana_E_Commerce_API.Entities.PaymentMethod", b =>
                {
                    b.HasOne("Banana_E_Commerce_API.Entities.Admin", "Admin")
                        .WithMany("PaymentMethods")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Banana_E_Commerce_API.Entities.Product", b =>
                {
                    b.HasOne("Banana_E_Commerce_API.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Banana_E_Commerce_API.Entities.Admin", "Admin")
                        .WithMany("Products")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Banana_E_Commerce_API.Entities.Storage", "Storage")
                        .WithMany("Products")
                        .HasForeignKey("StorageId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Banana_E_Commerce_API.Entities.ProductExportBill", b =>
                {
                    b.HasOne("Banana_E_Commerce_API.Entities.RequestExportProduct", "RequestExportProduct")
                        .WithMany("ProductExportBills")
                        .HasForeignKey("RequestExportProductId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Banana_E_Commerce_API.Entities.StorageManager", "StorageManager")
                        .WithMany("ProductExportBills")
                        .HasForeignKey("StorageManagerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Banana_E_Commerce_API.Entities.ProductExportDetail", b =>
                {
                    b.HasOne("Banana_E_Commerce_API.Entities.ProductExportBill", "ProductExportBill")
                        .WithMany("ProductExportDetails")
                        .HasForeignKey("ExportBillId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Banana_E_Commerce_API.Entities.ProductTier", "ProductTier")
                        .WithMany("ProductExportDetails")
                        .HasForeignKey("ProductTierId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Banana_E_Commerce_API.Entities.ProductFavorite", b =>
                {
                    b.HasOne("Banana_E_Commerce_API.Entities.Customer", "Customer")
                        .WithMany("ProductFavorites")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Banana_E_Commerce_API.Entities.ProductTier", "ProductTier")
                        .WithMany("ProductFavorites")
                        .HasForeignKey("ProductTierId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Banana_E_Commerce_API.Entities.ProductImage", b =>
                {
                    b.HasOne("Banana_E_Commerce_API.Entities.Product", "Product")
                        .WithMany("ProductImages")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Banana_E_Commerce_API.Entities.ProductTier", b =>
                {
                    b.HasOne("Banana_E_Commerce_API.Entities.Product", "Product")
                        .WithMany("ProductTiers")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Banana_E_Commerce_API.Entities.Tier", "Tier")
                        .WithMany("ProductTiers")
                        .HasForeignKey("TierId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Banana_E_Commerce_API.Entities.Rating", b =>
                {
                    b.HasOne("Banana_E_Commerce_API.Entities.Customer", "Customer")
                        .WithMany("Rates")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Banana_E_Commerce_API.Entities.ProductTier", "ProductTier")
                        .WithMany("Rates")
                        .HasForeignKey("ProductTierId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Banana_E_Commerce_API.Entities.RefreshToken", b =>
                {
                    b.HasOne("Banana_E_Commerce_API.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Banana_E_Commerce_API.Entities.RequestExportDetail", b =>
                {
                    b.HasOne("Banana_E_Commerce_API.Entities.ProductTier", "ProductTier")
                        .WithMany("RequestExportDetails")
                        .HasForeignKey("ProductTierId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Banana_E_Commerce_API.Entities.RequestExportProduct", "RequestExportProduct")
                        .WithMany("RequestExportDetails")
                        .HasForeignKey("RequestExportProductId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Banana_E_Commerce_API.Entities.RequestExportProduct", b =>
                {
                    b.HasOne("Banana_E_Commerce_API.Entities.Admin", "Admin")
                        .WithMany("RequestExportProducts")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Banana_E_Commerce_API.Entities.Order", "Order")
                        .WithOne("RequestExportProduct")
                        .HasForeignKey("Banana_E_Commerce_API.Entities.RequestExportProduct", "OrderId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Banana_E_Commerce_API.Entities.RequestImportDetail", b =>
                {
                    b.HasOne("Banana_E_Commerce_API.Entities.ProductTier", "ProductTier")
                        .WithMany("RequestImportDetails")
                        .HasForeignKey("ProductTierId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Banana_E_Commerce_API.Entities.RequestImportProduct", "RequestImportProduct")
                        .WithMany("RequestImportDetails")
                        .HasForeignKey("RequestImportProductId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Banana_E_Commerce_API.Entities.RequestImportProduct", b =>
                {
                    b.HasOne("Banana_E_Commerce_API.Entities.Admin", "Admin")
                        .WithMany("RequestImportProducts")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Banana_E_Commerce_API.Entities.Shipment", b =>
                {
                    b.HasOne("Banana_E_Commerce_API.Entities.Admin", "Admin")
                        .WithMany()
                        .HasForeignKey("AdminId");

                    b.HasOne("Banana_E_Commerce_API.Entities.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Banana_E_Commerce_API.Entities.ProductExportBill", "ProductExportBill")
                        .WithMany()
                        .HasForeignKey("ProductExportBillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Banana_E_Commerce_API.Entities.Shipper", "Shipper")
                        .WithMany("Shipments")
                        .HasForeignKey("ShipperId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Banana_E_Commerce_API.Entities.Shipper", b =>
                {
                    b.HasOne("Banana_E_Commerce_API.Entities.Admin", "Admin")
                        .WithMany()
                        .HasForeignKey("AdminId");

                    b.HasOne("Banana_E_Commerce_API.Entities.User", "User")
                        .WithOne("Shipper")
                        .HasForeignKey("Banana_E_Commerce_API.Entities.Shipper", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Banana_E_Commerce_API.Entities.Storage", b =>
                {
                    b.HasOne("Banana_E_Commerce_API.Entities.Admin", "User")
                        .WithMany()
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("Banana_E_Commerce_API.Entities.StorageManager", b =>
                {
                    b.HasOne("Banana_E_Commerce_API.Entities.Storage", "Storage")
                        .WithMany("StorageManagers")
                        .HasForeignKey("StorageId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Banana_E_Commerce_API.Entities.User", "User")
                        .WithOne("StorageManager")
                        .HasForeignKey("Banana_E_Commerce_API.Entities.StorageManager", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Banana_E_Commerce_API.Entities.User", b =>
                {
                    b.HasOne("Banana_E_Commerce_API.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
